dna_sequence = input("Введите последовательность ДНК: ").upper()
print("\n=== Анализ последовательности ДНК ===\n")
print(f"Последовательность в верхнем регистре: {dna_sequence}\n")
a_count = dna_sequence.count('A')
t_count = dna_sequence.count('T')
g_count = dna_sequence.count('G')
c_count = dna_sequence.count('C')
total_length = len(dna_sequence)
print("Подсчёт нуклеотидов:")
print(f"A: {a_count}")
print(f"T: {t_count}")
print(f"G: {g_count}")
print(f"C: {c_count}\n")
print(f"Общая длина: {total_length} нуклеотидов\n")
if total_length > 0:
    print("Процентное содержание:")
    print(f"A: {(a_count / total_length * 100):.1f}%")
    print(f"T: {(t_count / total_length * 100):.1f}%")
    print(f"G: {(g_count / total_length * 100):.1f}%")
    print(f"C: {(c_count / total_length * 100):.1f}%")